<?php
/**
 * @package   panopticon
 * @copyright Copyright (c)2023-2023 Nicholas K. Dionysopoulos / Akeeba Ltd
 * @license   GNU General Public License version 3, or later
 */

namespace Akeeba\Panopticon\View\Setup;


defined('AKEEBA') || die;

class Html extends \Awf\Mvc\DataView\Html
{
	public function display($tpl = null)
	{
		return parent::display($tpl); // TODO: Change the autogenerated stub
	}

}